# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, x_timestamps: List[int]=None, y_series: List[object]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param x_timestamps: The x_timestamps of this InlineResponse200.  # noqa: E501
        :type x_timestamps: List[int]
        :param y_series: The y_series of this InlineResponse200.  # noqa: E501
        :type y_series: List[object]
        """
        self.swagger_types = {
            'x_timestamps': List[int],
            'y_series': List[object]
        }

        self.attribute_map = {
            'x_timestamps': 'xTimestamps',
            'y_series': 'ySeries'
        }
        self._x_timestamps = x_timestamps
        self._y_series = y_series

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x_timestamps(self) -> List[int]:
        """Gets the x_timestamps of this InlineResponse200.


        :return: The x_timestamps of this InlineResponse200.
        :rtype: List[int]
        """
        return self._x_timestamps

    @x_timestamps.setter
    def x_timestamps(self, x_timestamps: List[int]):
        """Sets the x_timestamps of this InlineResponse200.


        :param x_timestamps: The x_timestamps of this InlineResponse200.
        :type x_timestamps: List[int]
        """

        self._x_timestamps = x_timestamps

    @property
    def y_series(self) -> List[object]:
        """Gets the y_series of this InlineResponse200.


        :return: The y_series of this InlineResponse200.
        :rtype: List[object]
        """
        return self._y_series

    @y_series.setter
    def y_series(self, y_series: List[object]):
        """Sets the y_series of this InlineResponse200.


        :param y_series: The y_series of this InlineResponse200.
        :type y_series: List[object]
        """

        self._y_series = y_series
