openapi: 3.0.0
info:
  title: Covid19 Extrapolation Data
  description: Provides an api for getting uptodate data about Covid19.
  version: 1.0.0
servers:
- url: http://localhost:3000
  description: None
paths:
  /all:
    get:
      summary: Timeline data for whole world
      operationId: all_get
      parameters:
      - name: extrapolation_days
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          default: 3
      - name: selected_countries
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: excluded_countries
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Invalid request
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /by_country:
    get:
      summary: Latest data for every countries
      operationId: by_country_get
      parameters:
      - name: extrapolation_days
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          default: 3
      - name: selected_countries
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: excluded_countries
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_1'
                x-content-type: application/json
        "400":
          description: Invalid request
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        xTimestamps:
          type: array
          items:
            type: integer
        ySeries:
          $ref: '#/components/schemas/inline_response_200_ySeries'
      example:
        xTimestamps:
        - 0
        - 0
        ySeries:
        - values:
          - 6
          - 6
          name: name
        - values:
          - 6
          - 6
          name: name
    inline_response_200_1:
      type: object
      properties:
        country:
          type: string
        active:
          type: integer
        confirmed:
          type: integer
        deaths:
          type: integer
        recovered:
          type: integer
        extrapolated_active:
          type: integer
        extrapolated_confirmed:
          type: integer
        extrapolated_deaths:
          type: integer
        extrapolated_recovered:
          type: integer
        extrapolated_social_distancing:
          type: integer
        extrapolated_without_social_distancing:
          type: integer
      example:
        country: country
        recovered: 5
        extrapolated_deaths: 7
        extrapolated_social_distancing: 3
        extrapolated_confirmed: 2
        extrapolated_without_social_distancing: 2
        active: 0
        extrapolated_recovered: 9
        confirmed: 6
        deaths: 1
        extrapolated_active: 5
    inline_response_200_ySeries:
      type: object
      properties:
        Active:
          type: array
          example:
            values:
            - 6
            - 6
          items:
            type: integer
        Confirmed:
          type: array
          example:
            values:
            - 6
            - 6
          items:
            type: integer
        Confirmed with social distancing:
          type: array
          example:
            values:
            - 6
            - 6
          items:
            type: integer
        Confirmed without social distancing:
          type: array
          example:
            values:
            - 6
            - 6
          items:
            type: integer
        Deaths:
          type: array
          example:
            values:
            - 6
            - 6
          items:
            type: integer
        Recovered:
          type: array
          example:
            values:
            - 6
            - 6
          items:
            type: integer

